# Generated by Django 3.2.9 on 2021-12-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftbuddyapi', '0002_auto_20211203_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='recipient',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
