# Generated by Django 3.2.9 on 2021-12-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftbuddyapi', '0003_auto_20211203_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='interest',
        ),
        migrations.AddField(
            model_name='recipient',
            name='interests',
            field=models.ManyToManyField(through='giftbuddyapi.RecipientInterest', to='giftbuddyapi.Interest'),
        ),
    ]
